/* =========================================================
   IMPOSSIBLE TOWER LIST — levels.js
   ZAKTUALIZOWANA LISTA — posortowana według difficulty
   ========================================================= */

const LAST_UPDATE = "01.08.2026";

const LEVELS = [
  {
    rank: 1,
    name: "Tower of Safe White Tower",
    creator: "ju_silvestre",
    verifier: "",
    difficulty: "High Error",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 2,
    name: "Tower of Jungle Gyms",
    creator: "Macloux, Higherthanblox, D_yni, Eccapin, Findabletag, Kinjiture, Melvinalsgamer, PoptartPunt, Empyrae, pacovepowered5, rohanmishrr, Yellow78Dog, SungazedUwU, Exhaustedsleepybear, Delukes51, CUGASTheLooney",
    verifier: "",
    difficulty: "Mid-High Error",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 3,
    name: "Chaotic Tower",
    creator: "zorloth1, vipsem, RagingEngineer, CreationIsntGood, D_yni, FindableTag, PoptartPunt, Delukes51, SungazedUwU",
    verifier: "",
    difficulty: "Mid-High Error",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 4,
    name: "Tower of Tedious Timings",
    creator: "sdt00",
    verifier: "",
    difficulty: "Low-Mid Error",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 5,
    name: "Tower of Collecting Dust Particles",
    creator: "Lukaye_19",
    verifier: "",
    difficulty: "Low Error",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 6,
    name: "Steeple of Frightening Raw Difficulty",
    creator: "andrewforkids",
    verifier: "",
    difficulty: "Low Error",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 7,
    name: "Tower of Ziggle Core",
    creator: "N/A",
    verifier: "",
    difficulty: "Bottom-Low Error",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 8,
    name: "EVIL TOWER '76",
    creator: "tintom495",
    verifier: "",
    difficulty: "Bottom Error",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 9,
    name: "Not Even Playable Gameplay",
    creator: "NameZerooo, SE5Y3QAY, MIXMENMIX, 10A_v, artemzartemz, benceiyibendy, kryception, MiniLagOOn, GameSion, computerboi3131, xXFighterofTimeXx",
    verifier: "",
    difficulty: "Baseline Error",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 10,
    name: "Citadel of Void",
    creator: "bLockerman666, Karinriine, IceNsalt, ciel_azulsky, Feodoric, tintom495, PPtTenshi, popop614, latomludo, macalads, Coatesultimate1, KittenLord420, nott_vy, Heksi",
    verifier: "",
    difficulty: "Peak Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 11,
    name: "Tower of Very Fun Obstacles",
    creator: "NoobsTheBestGuys, XxRed1ScorpionxX",
    verifier: "",
    difficulty: "Peak Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 12,
    name: "Tower of Vague Luminescence",
    creator: "glizzygladiattorrr, Adan3842, exhaustedsleepybear, SungazedUwU",
    verifier: "",
    difficulty: "High-Peak Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 13,
    name: "Tower of Existential Crisis",
    creator: "Kinjiture, dogwithabome, 4Nuln, pacovepowered5, Dasiohh",
    verifier: "",
    difficulty: "High Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 14,
    name: "Tower of Top Jumps Community Never Clear",
    creator: "N/A",
    verifier: "",
    difficulty: "High Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 15,
    name: "Tower of Absolute Corruption",
    creator: "AbyssalChaos",
    verifier: "",
    difficulty: "High Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 16,
    name: "Tower of Spiralling Fates: Side-B",
    creator: "ciel_azulsky, Nerve2X",
    verifier: "",
    difficulty: "Mid-High Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 17,
    name: "Tower of Unending Unforgiveness",
    creator: "Various Creators",
    verifier: "",
    difficulty: "Mid-High Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 18,
    name: "Tower of Parched and Exhausted",
    creator: "aminul2007",
    verifier: "",
    difficulty: "Mid-High Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 19,
    name: "Tower of Veiled Prophecy",
    creator: "Various Creators",
    verifier: "",
    difficulty: "Mid-High Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 20,
    name: "Tower of Ginga Glory",
    creator: "Nerve2X",
    verifier: "",
    difficulty: "Mid Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 21,
    name: "Tower of Memorization",
    creator: "LaimeRX",
    verifier: "",
    difficulty: "Mid Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 22,
    name: "Tower of Diabolical Strategem",
    creator: "Various Creators",
    verifier: "",
    difficulty: "Low-Mid Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 23,
    name: "Citadel of Wicked Boogers",
    creator: "PoptartPunt, Higherthanblox, Adan3842, SungazedUwU, Macloux, D_yni, FindableTag",
    verifier: "",
    difficulty: "Low Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 24,
    name: "Tower of Unrealistic Victory",
    creator: "One_GuestDream",
    verifier: "",
    difficulty: "Low Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 25,
    name: "Tuscan Tower",
    creator: "Satrrn",
    verifier: "",
    difficulty: "Bottom-Low Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 26,
    name: "Machine Girl Tower",
    creator: "wqntrr",
    verifier: "",
    difficulty: "Bottom Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 27,
    name: "Steeple of Eating Snakes",
    creator: "Various Creators",
    verifier: "",
    difficulty: "Bottom Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 28,
    name: "Tower of Sacrilegious Jumps",
    creator: "AbyssalChaos, brandchaos0001",
    verifier: "",
    difficulty: "Bottom Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 29,
    name: "Tower of The Drive Towards Human Limits",
    creator: "Adan3842, Findabletag, MonsterIsABlock",
    verifier: "",
    difficulty: "Baseline Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 30,
    name: "Tower of False Confidence",
    creator: "ashoutdev2, cristololo",
    verifier: "",
    difficulty: "Baseline Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 31,
    name: "Popsicle Tower",
    creator: "SouIIev",
    verifier: "",
    difficulty: "Baseline Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 32,
    name: "Tower of Chewing Gum",
    creator: "Subang_Jaya",
    verifier: "",
    difficulty: "Baseline Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 33,
    name: "Tower of Insane Zodiac",
    creator: "bilmoment",
    verifier: "",
    difficulty: "Peak Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 34,
    name: "Tower of Mushroom",
    creator: "Taste_Pepsi1, canteloupe3727",
    verifier: "",
    difficulty: "High-Peak Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 35,
    name: "ToV (Tower of Void)",
    creator: "bLockerman666, IceNsalt, ciel_azulsky, popop614, Feodoric, PPtTenshi",
    verifier: "",
    difficulty: "High Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 36,
    name: "ToTQFP (Tower of The Quest For Perfection)",
    creator: "4d9r, bLockerman666, BigScaryMonster10G",
    verifier: "",
    difficulty: "High Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 37,
    name: "Tower of The Concluding Run",
    creator: "sokol50",
    verifier: "",
    difficulty: "High Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 38,
    name: "Hellish Eextermination Labyrinth",
    creator: "AddisonJudah, Tetrix_Masterll, yuienaaaa, Hyperfantasies",
    verifier: "",
    difficulty: "High Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 39,
    name: "Tower of Flotage",
    creator: "",
    verifier: "",
    difficulty: "Mid-High Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 40,
    name: "Tower of Multiversal Dream Archive",
    creator: "ZePlayerSlayer",
    verifier: "",
    difficulty: "Mid-High Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 41,
    name: "Tower of It Never Ends",
    creator: "ciel_azulsky",
    verifier: "MonsterIsABlock",
    difficulty: "Mid Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 42,
    name: "STONE: Reborn",
    creator: "IceNsalt, Zakki",
    verifier: "MonsterIsABlock",
    difficulty: "Mid Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 43,
    name: "ToID (Tower of Impending Doom)",
    creator: "pczm1, Forstaken2008xs, mikolajole, skitsuna, walroooos, Celest_Z, Demolisher_11",
    verifier: "greenbean1421",
    difficulty: "Low-Mid Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 44,
    name: "ToW (Tower of Wigglecore)",
    creator: "ScorpioexLOLez, kkdpracticeacc",
    verifier: "BoomSasok",
    difficulty: "Low-Mid Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 45,
    name: "ToMH (Tower of Monochromatic Haze)",
    creator: "Gehadimadm, tweet2a, Forstaken2008xs",
    verifier: "Gehadimad",
    difficulty: "Low-Mid Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 46,
    name: "Tower of Rebirth The End",
    creator: "Polovnik30, Sokol50",
    verifier: "",
    difficulty: "Low-Mid Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 47,
    name: "ToMIH (Tower of My Inner Hatred)",
    creator: "Reimu Hakurei, Kinjiture, BFFPikachu",
    verifier: "ZePlayerSlayer",
    difficulty: "Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 48,
    name: "ToSF (Tower of Spiralling Fates)",
    creator: "ciel_azulsky",
    verifier: "MonsterIsABlock",
    difficulty: "Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 49,
    name: "CoCBF (Citadel of Cold Blooded Fatality)",
    creator: "n_rtex, a6iq1",
    verifier: "BlackportTransport",
    difficulty: "Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 50,
    name: "OoUS (Obelisk of Unrealistic Sightings)",
    creator: "Apple_FlavoredWater, yuienaaaa, CamronSkilIz, Killer818616",
    verifier: "Pyuruw",
    difficulty: "Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 51,
    name: "ToCB (Tower of Celestial Bloom)",
    creator: "zkv07, glizzygladiattorrr",
    verifier: "hyperionblades",
    difficulty: "Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 52,
    name: "ToQU (Tower of Qwerty Uiop)",
    creator: "Purple_BaconHair",
    verifier: "jeang4me",
    difficulty: "Bottom-Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 53,
    name: "CoTEC (Citadel of The Eternal Calamity)",
    creator: "susplayerslayer",
    verifier: "Marqulitt",
    difficulty: "Bottom-Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 54,
    name: "CoIV (Citadel of Infinite Void)",
    creator: "bLockerman666, IceNsalt, popop614, ciel_azulsky, PPtTenshi, latomludo, Heksi, nott_vy, skitsuna, mrgamingpotato1",
    verifier: "skitsuna",
    difficulty: "Bottom-Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 55,
    name: "ToBF (Tower of Blind Fate)",
    creator: "Nosav",
    verifier: "tinenderman",
    difficulty: "Bottom-Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 56,
    name: "ToP (Tower of Paradise)",
    creator: "Macloux",
    verifier: "Yazmania_1m",
    difficulty: "Bottom-Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 57,
    name: "ToMIM (Tower of Maybe In Mumbai)",
    creator: "Naz0dial, Stitch, Hexium, brub, arik21, az77, zkv07, asAGAIN, nortex, dom, ChillUltralight, spear, geo, twossed.173, NadiPlaysss",
    verifier: "ChillUltralight",
    difficulty: "Bottom-Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 58,
    name: "ToWC (Tower of Withered Consensus)",
    creator: "glizzygladiattorrr",
    verifier: "glizzygladiattorrr",
    difficulty: "Bottom Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 59,
    name: "TT (Target Tower)",
    creator: "DukeQD, Forstaken2008xs, Tritone246",
    verifier: "player0v0",
    difficulty: "Bottom Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 60,
    name: "ToZS (Tower of Zen Surplus)",
    creator: "ciel_azulsky, skitsuna",
    verifier: "SeeRyanplayroblox",
    difficulty: "Bottom Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 61,
    name: "ToTT (Tower of Twenty Two)",
    creator: "mccatster, jeremylightbulb, zelirium, ghoned, G1adit, carmeniscool12525_2",
    verifier: "carmeniscool12525_2",
    difficulty: "Bottom Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 62,
    name: "3008-T (3008 Tower)",
    creator: "pczm1",
    verifier: "ChillUltralight",
    difficulty: "Bottom Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 63,
    name: "IKEA (Ikea Tower)",
    creator: "Higherthanblox",
    verifier: "MonsterIsABlock",
    difficulty: "Bottom Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 64,
    name: "Mini and Not Great Obelisk of Mini and Not Great Obelisk",
    creator: "joelkoot, Tomasklimt, damadman11, Renzovanhooren, fedde201, rutra6665, Wesleytjes",
    verifier: "",
    difficulty: "Bottom Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 65,
    name: "ToSD (Tower of Sudden Death)",
    creator: "WaterMakeer, CosmikChaos",
    verifier: "skitsuna",
    difficulty: "Baseline Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
];
