/* =========================================================
   IMPOSSIBLE TOWER LIST — levels.js
   THIS IS THE ONLY FILE YOU NEED TO EDIT.

   Each tower is one object { ... } in the LEVELS array below.
   Fields:

     rank         (required) — position in ranking, 1 = hardest
     name         (required) — tower name
     creator      (required) — tower creator(s)
     verifier     (optional) — who verified the tower (empty = unverified)
     difficulty   (optional) — EToH-style difficulty
     videoId      (optional) — YouTube link OR 11-character video ID
     worldRecord  (optional) — best completion, e.g. "Floor 7", "N/A"
     robloxLink   (optional) — link to the Roblox place where this
                                tower is located, e.g.
                                "https://www.roblox.com/games/XXXXXXXX/Place-Name"

   Order of objects in the array doesn't matter — the page
   sorts them by "rank". You can have unlimited entries.
   ========================================================= */

const LAST_UPDATE = "01.08.2026";

const LEVELS = [
  {
    rank: 1,
    name: "Tower of Safe White Tower",
    creator: "ju_silvestre",
    verifier: "",
    difficulty: "High Error",
    videoId: "nJ57W9aWwD0",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/101044284168858/Tower-of-Safe-White-Tower",
  },
  {
    rank: 2,
    name: "Tower of Jungle Gyms",
    creator: "Macloux, Higherthanblox, D_yni, Eccapin, Findabletag, Kinjiture, Melvinalsgamer, PoptartPunt, Empyrae, pacovepowered5, rohanmishrr, Yellow78Dog, SungazedUwU, Exhaustedsleepybear, Delukes51, CUGASTheLooney",
    verifier: "",
    difficulty: "Mid-High Error",
    videoId: "B0VpzdvwrC0",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/99982773118045/Tower-of-Jungle-Gyms-The-Big-Climb#ropro-quick-search",
  },
  {
    rank: 3,
    name: "Chaotic Tower",
    creator: "zorloth1, vipsem, RagingEngineer, CreationIsntGood, D_yni, FindableTag, PoptartPunt, Delukes51, SungazedUwU",
    verifier: "",
    difficulty: "Mid-High Error",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/5684674542/Chaotic-Tower-R",
  },
  {
    rank: 4,
    name: "Tower of Crazy Snakes",
    creator: "megabruhfart",
    verifier: "",
    difficulty: "Mid Error",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 5,
    name: "Tower of Tedious Timings",
    creator: "sdt00",
    verifier: "",
    difficulty: "Low-Mid Error",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/119994535255674/Tower-of-Tedious-Timings",
  },
  {
    rank: 6,
    name: "Tower of Collecting Dust Particles",
    creator: "Lukaye_19",
    verifier: "",
    difficulty: "Low Error",
    videoId: "l72CfV-I1_Y",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/138794791429163/Tower-of-Collected-Dust-Particles",
  },
  {
    rank: 7,
    name: "Steeple of Frightening Raw Difficulty",
    creator: "andrewforkids",
    verifier: "",
    difficulty: "Low Error",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/7016681580/Steeple-of-Frightening-Raw-Difficulty",
  },
  {
    rank: 8,
    name: "Tower of Ziggle Core",
    creator: "N/A",
    verifier: "",
    difficulty: "Bottom-Low Error",
    videoId: "EO_kYW30LCg",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/89993867711798/Tower-of-Ziggle-Core",
  },
  {
    rank: 9,
    name: "EVIL TOWER '76",
    creator: "tintom495",
    verifier: "",
    difficulty: "Bottom Error",
    videoId: "XFh1iB1QTho",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/17781078059/EVIL-TOWER-76",
  },
  {
    rank: 10,
    name: "Not Even Playable Gameplay",
    creator: "NameZerooo, SE5Y3QAY, MIXMENMIX, 10A_v, artemzartemz, benceiyibendy, kryception, MiniLagOOn, GameSion, computerboi3131, xXFighterofTimeXx",
    verifier: "",
    difficulty: "Baseline Error",
    videoId: "U1nDh0HO9A4",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/130670383361152/Not-Even-Playable-Gameplay",
  },
  {
    rank: 11,
    name: "Citadel of Void",
    creator: "bLockerman666, Karinriine, IceNsalt, ciel_azulsky, Feodoric, tintom495, PPtTenshi, popop614, latomludo, macalads, Coatesultimate1, KittenLord420, nott_vy, Heksi",
    verifier: "",
    difficulty: "Peak Nil",
    videoId: "bJPgQlqkQxI",
    worldRecord: "Floor 7",
    robloxLink: "https://www.roblox.com/games/4597361034/Citadel-of-Void-OFFICIAL",
  },
  {
    rank: 12,
    name: "Tower of Very Fun Obstacles",
    creator: "NoobsTheBestGuys, XxRed1ScorpionxX",
    verifier: "",
    difficulty: "Peak Nil",
    videoId: "Vj5sFQq7mKA&t=4s",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 13,
    name: "Tower of Vague Luminescence",
    creator: "glizzygladiattorrr, Adan3842, exhaustedsleepybear, SungazedUwU",
    verifier: "",
    difficulty: "High-Peak Nil",
    videoId: "s5vJ6ha2Luo",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/9024799067/Tower-of-Vague-Luminescence",
  },
  {
    rank: 14,
    name: "Tower of Existential Crisis",
    creator: "Kinjiture, dogwithabome, 4Nuln, pacovepowered5, Dasiohh",
    verifier: "",
    difficulty: "High Nil",
    videoId: "YUkjDZra0t8",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/10712971259/Tower-of-Existential-Crisis",
  },
  {
    rank: 15,
    name: "Tower of Top Jumps Community Never Clear",
    creator: "N/A",
    verifier: "",
    difficulty: "High Nil",
    videoId: "w092tls5Wq0",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 16,
    name: "Tower of Absolute Corruption",
    creator: "AbyssalChaos",
    verifier: "",
    difficulty: "High Nil",
    videoId: "L6JZNV7QveQ",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/8375008730/Tower-of-Absolute-Corruption",
  },
  {
    rank: 17,
    name: "Tower of Spiralling Fates: Side-B",
    creator: "ciel_azulsky, Nerve2X",
    verifier: "",
    difficulty: "Mid-High Nil",
    videoId: "heTlDt2DhLM",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 18,
    name: "Tower of Unending Unforgiveness",
    creator: "hhhjhjjjjijijj, shuiggAF, babypizza34",
    verifier: "",
    difficulty: "Mid-High Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 19,
    name: "Tower of Parched and Exhausted",
    creator: "aminul2007",
    verifier: "",
    difficulty: "Mid-High Nil",
    videoId: "2nQ8j79hxLI",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/133133185725636/Tower-of-Parched-and-Exhausted",
  },
  {
    rank: 20,
    name: "Tower of Veiled Prophecy",
    creator: "TobiasHeroofRoblox, EEEEEEEEEEGHGHI, artemzartemz, obbylordd, microwavium",
    verifier: "",
    difficulty: "Mid-High Nil",
    videoId: "ARoG4ZsKOpw",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/121475110039668/Tower-of-Veiled-Prophecy",
  },
  {
    rank: 21,
    name: "Tower of Ginga Glory",
    creator: "Nerve2X",
    verifier: "",
    difficulty: "Mid Nil",
    videoId: "DInkLVb9Ciw",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/18202705587/Tower-of-Ginga-Glory",
  },
  {
    rank: 22,
    name: "Tower of Memorization",
    creator: "LaimeRX",
    verifier: "",
    difficulty: "Mid Nil",
    videoId: "8AXNvlqE44w",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/7023281752/tower-of-memorization",
  },
  {
    rank: 23,
    name: "Tower of Dead Grandma 2",
    creator: "ZachTheTrxhard, JohnTheTrxhard, Senztrix",
    verifier: "",
    difficulty: "Low-Mid Nil",
    videoId: "ZlIcCWCxzpk",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/10436183562/Tower-of-Dead-Grandma-2",
  },
  {
    rank: 24,
    name: "Citadel of Wicked Boogers",
    creator: "PoptartPunt, Higherthanblox, Adan3842, SungazedUwU, Macloux, D_yni, FindableTag",
    verifier: "",
    difficulty: "Low Nil",
    videoId: "RLnT4QqycoQ",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/123328980290815/Citadel-of-Wicked-Booger",
  },
  {
    rank: 25,
    name: "Tower of Unrealistic Victory",
    creator: "One_GuestDream",
    verifier: "",
    difficulty: "Low Nil",
    videoId: "_0-6209Rl2Y",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/13723458889/Tower-of-Unrealistic-Victory",
  },
  {
    rank: 26,
    name: "Tuscan Tower",
    creator: "Satrrn",
    verifier: "",
    difficulty: "Bottom-Low Nil",
    videoId: "sNJYG8mWeTI",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/130653473431229/tuscan-tower",
  },
  {
    rank: 27,
    name: "Machine Girl Tower",
    creator: "wqntrr",
    verifier: "",
    difficulty: "Bottom Nil",
    videoId: "g7pWf5pmRHw",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 28,
    name: "Steeple of Eating Snakes",
    creator: "Twolova, Chanlack, Dragongoldking0, KING_JIJO",
    verifier: "",
    difficulty: "Bottom Nil",
    videoId: "Oc03ZYk2cKg",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/121990219081062/Steeple-of-Eating-Snakes",
  },
  {
    rank: 29,
    name: "Tower of Sacrilegious Jumps",
    creator: "AbyssalChaos, brandchaos0001",
    verifier: "",
    difficulty: "Bottom Nil",
    videoId: "iqfXceSezR8",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/11700494590/Tower-of-Sacrilegious-Jumps",
  },
  {
    rank: 30,
    name: "Tower of The Drive Towards Human Limits",
    creator: "Adan3842, Findabletag, MonsterIsABlock",
    verifier: "",
    difficulty: "Baseline Nil",
    videoId: "AceEID7TVKc",
    worldRecord: "Floor 8",
    robloxLink: "https://www.roblox.com/games/125252864219980/Tower-of-The-Drive-Towards-Human-Limits",
  },
  {
    rank: 31,
    name: "Tower of False Confidence",
    creator: "ashoutdev2, cristololo",
    verifier: "",
    difficulty: "Baseline Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/118250523983734/tower-of-generation-succes",
  },
  {
    rank: 32,
    name: "Popsicle Tower",
    creator: "SouIIev",
    verifier: "",
    difficulty: "Baseline Nil",
    videoId: "oLTNVsQjJxE",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 33,
    name: "Tower of Chewing Gum",
    creator: "Subang_Jaya",
    verifier: "",
    difficulty: "Baseline Nil",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/18395822264/Tower-of-Chewing-Gum",
  },
  {
    rank: 34,
    name: "Tower of Insane Zodiac",
    creator: "bilmoment",
    verifier: "",
    difficulty: "Peak Unreal",
    videoId: "5El1ZYt0zNA",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/91634804321932/Tower-of-Insane-Zodiac",
  },
  {
    rank: 35,
    name: "Tower of Mushroom",
    creator: "Taste_Pepsi1, canteloupe3727",
    verifier: "",
    difficulty: "High-Peak Unreal",
    videoId: "adSiolrNJjY",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/11857764752/Tower-of-Mushroom#ropro-quick-play",
  },
  {
    rank: 36,
    name: "Tower of Void",
    creator: "bLockerman666, IceNsalt, ciel_azulsky, popop614, Feodoric, PPtTenshi",
    verifier: "",
    difficulty: "High Unreal",
    videoId: "T-kOe8L6uw8",
    worldRecord: "Floor 9",
    robloxLink: "https://www.roblox.com/games/88462999400021/Tower-of-Void-practice",
  },
  {
    rank: 37,
    name: "(Tower of The Quest For Perfection",
    creator: "4d9r, bLockerman666, BigScaryMonster10G",
    verifier: "",
    difficulty: "High Unreal",
    videoId: "vMOpTTcdIVk",
    worldRecord: "Floor 8",
    robloxLink: "https://www.roblox.com/games/14860104753/Tower-of-The-Quest-For-Perfection-Fixed",
  },
  {
    rank: 38,
    name: "Tower of The Concluding Run",
    creator: "sokol50",
    verifier: "",
    difficulty: "High Unreal",
    videoId: "https://www.youtube.com/watch?v=aayo6JJA0FM&t=1s",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 39,
    name: "Hellish Extermination Labyrinth",
    creator: "AddisonJudah, Tetrix_Masterll, yuienaaaa, Hyperfantasies",
    verifier: "",
    difficulty: "High Unreal",
    videoId: "kLb26I6PKNo",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 40,
    name: "Tower of Flotage",
    creator: "cIoverdove",
    verifier: "",
    difficulty: "Mid-High Unreal",
    videoId: "https://www.youtube.com/watch?v=zeW5kxeKLk8&list=RDzeW5kxeKLk8&start_radio=1&t=222s",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 41,
    name: "Tower of Multiversal Dream Archive",
    creator: "ZePlayerSlayer",
    verifier: "",
    difficulty: "Mid-High Unreal",
    videoId: "IONOfb8s9xs",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/109123863452692/Tower-of-Multiversal-Dream-Archive",
  },
  {
    rank: 42,
    name: "Tower of It Never Ends",
    creator: "ciel_azulsky",
    verifier: "MonsterIsABlock",
    difficulty: "Mid Unreal",
    videoId: "bwDpQOuQaGg",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/107705095969573/tower-of-IT-NEVER-ENDS",
  },
  {
    rank: 43,
    name: "STONE: Reborn",
    creator: "IceNsalt, Zakki",
    verifier: "MonsterIsABlock",
    difficulty: "Mid Unreal",
    videoId: "N4B9qvfS8qQ",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/5711190403/The-S-T-O-N-E-Facility",
  },
  {
    rank: 44,
    name: "Tower of Impending Doom",
    creator: "pczm1, Forstaken2008xs, mikolajole, skitsuna, walroooos, Celest_Z, Demolisher_11",
    verifier: "greenbean1421",
    difficulty: "Low-Mid Unreal",
    videoId: "DRGmoqF1T_E",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/15177865210/Tower-of-Impending-Doom#!/about",
  },
  {
    rank: 45,
    name: "Tower of Wigglecore",
    creator: "ScorpioexLOLez, kkdpracticeacc",
    verifier: "BoomSasok",
    difficulty: "Low-Mid Unreal",
    videoId: "nj2vwu0LeG8",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/15873244701/JToH-The-Eternal-Abyss",
  },
  {
    rank: 46,
    name: "Tower of Monochromatic Haze",
    creator: "Gehadimadm, tweet2a, Forstaken2008xs",
    verifier: "Gehadimad",
    difficulty: "Low-Mid Unreal",
    videoId: "HxCV-_zrLW0",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/117307574423766/Tower-of-Monochromatic-Haze-List-Version",
  },
  {
    rank: 47,
    name: "Tower of Rebirth The End",
    creator: "Polovnik30, Sokol50",
    verifier: "",
    difficulty: "Low-Mid Unreal",
    videoId: "eKYZ4g6Mfkw",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/70581657896182/Tower-of-Rebirth-the-End",
  },
  {
    rank: 48,
    name: "Tower of My Inner Hatred)",
    creator: "Reimu Hakurei, Kinjiture, BFFPikachu",
    verifier: "ZePlayerSlayer",
    difficulty: "Low Unreal",
    videoId: "CZzEPcEtwNU",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/119663832848907/Tower-of-My-Inner-Hatred",
  },
  {
    rank: 49,
    name: "Tower of Spiralling Fates",
    creator: "ciel_azulsky",
    verifier: "MonsterIsABlock",
    difficulty: "Low Unreal",
    videoId: "Wc3IJivXjfE",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/130741996193452/Tower-of-Spiralling-Fates",
  },
  {
    rank: 50,
    name: "Citadel of Cold Blooded Fatality",
    creator: "n_rtex, a6iq1",
    verifier: "BlackportTransport",
    difficulty: "Low Unreal",
    videoId: "foOtLcnyII0",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/71138470084002/Citadel-of-Cold-Blooded-Fatality",
  },
  {
    rank: 51,
    name: "Obelisk of Unrealistic Sightings",
    creator: "Apple_FlavoredWater, yuienaaaa, CamronSkilIz, Killer818616",
    verifier: "Pyuruw",
    difficulty: "Low Unreal",
    videoId: "C2J7jaC-pt0",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/4777161742/Obelisk-of-Unrealistic-Sightings",
  },
  {
    rank: 52,
    name: "Tower of Celestial Bloom",
    creator: "zkv07, glizzygladiattorrr",
    verifier: "hyperionblades",
    difficulty: "Low Unreal",
    videoId: "I5QVrxvPaXY&t",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/140232542804431/Tower-of-Celestial-Bloom",
  },
  {
    rank: 53,
    name: "Tower of Qwerty Uiop",
    creator: "Purple_BaconHair",
    verifier: "jeang4me",
    difficulty: "Bottom-Low Unreal",
    videoId: "v5f32f4Poks&t=51s",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/7769438539/Tower-of-Qwerty-Uiop",
  },
  {
    rank: 54,
    name: "Citadel of The Eternal Calamity",
    creator: "susplayerslayer",
    verifier: "Marqulitt",
    difficulty: "Bottom-Low Unreal",
    videoId: "cZefNeSBC40",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/12121834605/The-Eternal-Calamity-ULTIMATE",
  },
  {
    rank: 55,
    name: "Citadel of Infinite Void",
    creator: "bLockerman666, IceNsalt, popop614, ciel_azulsky, PPtTenshi, latomludo, Heksi, nott_vy, skitsuna, mrgamingpotato1",
    verifier: "skitsuna",
    difficulty: "Bottom-Low Unreal",
    videoId: "Mtcliw0KJ4w",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/10199085458/Citadel-of-Infinite-Void",
  },
  {
    rank: 56,
    name: "Tower of Blind Fate",
    creator: "Nosav",
    verifier: "tinenderman",
    difficulty: "Bottom-Low Unreal",
    videoId: "6xzPARlwnio",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/3100988051/Tower-of-Blind-Fate",
  },
  {
    rank: 57,
    name: "Tower of Paradise",
    creator: "Macloux",
    verifier: "Yazmania_1m",
    difficulty: "Bottom-Low Unreal",
    videoId: "NkRtXvFl-lA",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/10541580790/Tower-of-Paradise",
  },
  {
    rank: 58,
    name: "Tower of Maybe In Mumbai",
    creator: "Naz0dial, Stitch, Hexium, brub, arik21, az77, zkv07, asAGAIN, nortex, dom, ChillUltralight, spear, geo, twossed.173, NadiPlaysss",
    verifier: "ChillUltralight",
    difficulty: "Bottom-Low Unreal",
    videoId: "_e93li9cdDE",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/83052485504037/Tower-of-Maybe-in-Mumbai",
  },
  {
    rank: 59,
    name: "Tower of Withered Consensus",
    creator: "glizzygladiattorrr",
    verifier: "glizzygladiattorrr",
    difficulty: "Bottom Unreal",
    videoId: "DLKMIGM6mS8",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/85794013389625/Tower-of-Withered-Consensus",
  },
  {
    rank: 60,
    name: "Target Tower",
    creator: "DukeQD, Forstaken2008xs, Tritone246",
    verifier: "player0v0",
    difficulty: "Bottom Unreal",
    videoId: "UiK6pKgHGpU",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/16730891689/",
  },
  {
    rank: 61,
    name: "Tower of Zen Surplus",
    creator: "ciel_azulsky, skitsuna",
    verifier: "SeeRyanplayroblox",
    difficulty: "Bottom Unreal",
    videoId: "AT90nqEX0NE",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 62,
    name: "Tower of Twenty Two",
    creator: "mccatster, jeremylightbulb, zelirium, ghoned, G1adit, carmeniscool12525_2",
    verifier: "carmeniscool12525_2",
    difficulty: "Bottom Unreal",
    videoId: "beqUfnw8dGQgHudh",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 63,
    name: "3008 Tower",
    creator: "pczm1",
    verifier: "ChillUltralight",
    difficulty: "Bottom Unreal",
    videoId: "rO8Czv0HcNk&t",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/17401926899/3008-Tower",
  },
  {
    rank: 64,
    name: "Ikea Tower",
    creator: "Higherthanblox",
    verifier: "MonsterIsABlock",
    difficulty: "Bottom Unreal",
    videoId: "fpJmckiIzFw",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/17379816541/Sweden-Tower",
  },
  {
    rank: 65,
    name: "Mini and Not Great Obelisk of Mini and Not Great Obelisk",
    creator: "joelkoot, Tomasklimt, damadman11, Renzovanhooren, fedde201, rutra6665, Wesleytjes",
    verifier: "",
    difficulty: "Bottom Unreal",
    videoId: "ow9Dcpf61f0",
    worldRecord: "finale stretch",
    robloxLink: "",
  },
  {
    rank: 66,
    name: "Tower of Sudden Death",
    creator: "WaterMakeer, CosmikChaos",
    verifier: "skitsuna",
    difficulty: "Baseline Unreal",
    videoId: "75VZzOgVyHc",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/18603968759/Community-Top-Towers",
  },
];
