/* =========================================================
   IMPOSSIBLE TOWER LIST — levels.js
   THIS IS THE ONLY FILE YOU NEED TO EDIT.

   Each tower is one object { ... } in the LEVELS array below.
   Fields:

     rank         (required) — position in ranking, 1 = hardest
     name         (required) — tower name
     creator      (required) — tower creator(s)
     verifier     (optional) — who verified the tower (empty = unverified)
     difficulty   (optional) — EToH-style difficulty
     videoId      (optional) — YouTube link OR 11-character video ID
     worldRecord  (optional) — best completion, e.g. "Floor 7", "N/A"
     robloxLink   (optional) — link to the Roblox place where this
                                tower is located, e.g.
                                "https://www.roblox.com/games/XXXXXXXX/Place-Name"

   Order of objects in the array doesn't matter — the page
   sorts them by "rank". You can have unlimited entries.
   ========================================================= */

const LAST_UPDATE = "29.07.2026";

const LEVELS = [
  {
    rank: 1,
    name: "Tower of Jungle Gyms",
    creator: "Macloux, Higherthanblox, D_yni, Eccapin, Findabletag, Kinjiture, Melvinalsgamer, PoptartPunt, Empyrae, pacovepowered5, rohanmishrr, Yellow78Dog, SungazedUwU, Exhaustedsleepybear, Delukes51, CUGASTheLooney",
    verifier: "",
    difficulty: "Mid-High Error",
    videoId: "B0VpzdvwrC0",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 2,
    name: "Citadel of Void",
    creator: "bLockerman666, Karinriine, IceNsalt, ciel_azulsky, Feodoric, tintom495, PPtTenshi, popop614, latomludo, macalads, Coatesultimate1, KittenLord420, nott_vy, Heksi",
    verifier: "",
    difficulty: "Peak Nil",
    videoId: "bJPgQlqkQxI",
    worldRecord: "Floor 7",
    robloxLink: "",
  },
  {
    rank: 3,
    name: "Tower of It Never Ends",
    creator: "ciel_azulsky",
    verifier: "MonsterIsABlock",
    difficulty: "Mid Unreal",
    videoId: "bwDpQOuQaGg",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/107705095969573/tower-of-IT-NEVER-ENDS",
  },
  {
    rank: 4,
    name: "STONE: Reborn",
    creator: "IceNsalt, Zakki",
    verifier: "MonsterIsABlock",
    difficulty: "Mid Unreal",
    videoId: "N4B9qvfS8qQ",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/5711190403/The-S-T-O-N-E-Facility",
  },
  {
    rank: 5,
    name: "ToID (Tower of Impending Doom)",
    creator: "Various Creators",
    verifier: "greenbean1421",
    difficulty: "Low-Mid Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/15177865210/Tower-of-Impending-Doom#!/about",
  },
  {
    rank: 6,
    name: "ToW (Tower of Wigglecore)",
    creator: "ScorpioexLOLez, kkdpracticeacc",
    verifier: "BoomSasok",
    difficulty: "Low-Mid Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/15873244701/JToH-The-Eternal-Abyss",
  },
  {
    rank: 7,
    name: "ToMH (Tower of Monochromatic Haze)",
    creator: "Various Creators",
    verifier: "Gehadimad",
    difficulty: "Low-Mid Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/117307574423766/Tower-of-Monochromatic-Haze-List-Version",
  },
  {
    rank: 8,
    name: "ToMIH (Tower of My Inner Hatred)",
    creator: "Various Creators",
    verifier: "ZePlayerSlayer",
    difficulty: "Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/119663832848907/Tower-of-My-Inner-Hatred",
  },
  {
    rank: 9,
    name: "ToSF (Tower of Spiralling Fates)",
    creator: "ciel_azulsky",
    verifier: "MonsterIsABlock",
    difficulty: "Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/130741996193452/Tower-of-Spiralling-Fates",
  },
  {
    rank: 10,
    name: "CoCBF (Citadel of Cold Blooded Fatality)",
    creator: "n_rtex, a6iq1",
    verifier: "BlackportTransport",
    difficulty: "Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/71138470084002/Citadel-of-Cold-Blooded-Fatality",
  },
  {
    rank: 11,
    name: "OoUS (Obelisk of Unrealistic Sightings)",
    creator: "",
    verifier: "Pyuruw",
    difficulty: "Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/4777161742/Obelisk-of-Unrealistic-Sightings",
  },
  {
    rank: 12,
    name: "ToCB (Tower of Celestial Bloom)",
    creator: "zkv07, glizzygladiattorrr",
    verifier: "hyperionblades",
    difficulty: "Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/140232542804431/Tower-of-Celestial-Bloom",
  },
  {
    rank: 13,
    name: "ToQU (Tower of Qwerty Uiop)",
    creator: "Purple_BaconHair",
    verifier: "jeang4me",
    difficulty: "Bottom-Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/7769438539/Tower-of-Qwerty-Uiop",
  },
  {
    rank: 14,
    name: "CoTEC (Citadel of The Eternal Calamity)",
    creator: "susplayerslayer",
    verifier: "Marqulitt",
    difficulty: "Bottom-Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/12121834605/The-Eternal-Calamity-ULTIMATE",
  },
  {
    rank: 15,
    name: "CoIV (Citadel of Infinite Void)",
    creator: "bLockerman666, IceNsalt, popop614, ciel_azulsky, PPtTenshi, latomludo, Heksi, nott_vy, skitsuna, mrgamingpotato1",
    verifier: "skitsuna",
    difficulty: "Bottom-Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/10199085458/Citadel-of-Infinite-Void",
  },
  {
    rank: 16,
    name: "ToBF (Tower of Blind Fate)",
    creator: "Nosav",
    verifier: "tinenderman",
    difficulty: "Bottom-Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/3100988051/Tower-of-Blind-Fate",
  },
  {
    rank: 17,
    name: "ToP (Tower of Paradise)",
    creator: "Macloux",
    verifier: "Yazmania_1m",
    difficulty: "Bottom-Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/10541580790/Tower-of-Paradise",
  },
  {
    rank: 18,
    name: "ToMIM (Tower of Maybe In Mumbai)",
    creator: "Various Creators",
    verifier: "ChillUltralight",
    difficulty: "Bottom-Low Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/83052485504037/Tower-of-Maybe-in-Mumbai",
  },
  {
    rank: 19,
    name: "ToWC (Tower of Withered Consensus)",
    creator: "glizzygladiattorrr",
    verifier: "glizzygladiattorrr",
    difficulty: "Bottom Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/85794013389625/Tower-of-Withered-Consensus",
  },
  {
    rank: 20,
    name: "TT (Target Tower)",
    creator: "Various Creators",
    verifier: "player0v0",
    difficulty: "Bottom Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/16730891689/",
  },
  {
    rank: 21,
    name: "ToZS (Tower of Zen Surplus)",
    creator: "ciel_azulsky, skitsuna",
    verifier: "SeeRyanplayroblox",
    difficulty: "Bottom Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 22,
    name: "ToTT (Tower of Twenty Two)",
    creator: "Various Creators",
    verifier: "carmeniscool12525_2",
    difficulty: "Bottom Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "",
  },
  {
    rank: 23,
    name: "3008-T (3008 Tower)",
    creator: "pczm1",
    verifier: "ChillUltralight",
    difficulty: "Bottom Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/17401926899/3008-Tower",
  },
  {
    rank: 24,
    name: "IKEA (Ikea Tower)",
    creator: "Higherthanblox",
    verifier: "MonsterIsABlock",
    difficulty: "Bottom Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/17379816541/Sweden-Tower",
  },
  {
    rank: 25,
    name: "ToSD (Tower of Sudden Death)",
    creator: "WaterMakeer, CosmikChaos",
    verifier: "skitsuna",
    difficulty: "Baseline Unreal",
    videoId: "",
    worldRecord: "N/A",
    robloxLink: "https://www.roblox.com/games/18603968759/Community-Top-Towers",
  },
];
